name: Vite Wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Check for Cached Webassembly Dependencies
      id: cache-wasm-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-wasm-deps
      with:
        path: |
          ~/.cargo/bin/wasm-pack
          ~/.cargo/bin/wasm-opt
        key: ${{ runner.os }}-wasm-deps

    - name: Build Webassembly Dependencies
      run: |
        cargo install wasm-pack
        cargo install wasm-opt
      if: steps.cache-wasm-deps.outputs.cache-hit != 'true'

    - name: Set Up Github Pages
      uses: actions/configure-pages@v3

    - name: Set Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Vite Build
      run: |
        npm install
        npm run wasm
        npm run build

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1